const a = () => 'a';
const b = () => 'b';
const c = () => 'c';
const d = () => 'd';
const e = () => 'e';
const f = () => 'f';
const g = () => 'g';
const h = () => 'h';
const i = () => 'i';
const j = () => 'j';
const k = () => 'k';
const l = () => 'l';
const m = () => 'm';
const n = () => 'n';
const o = () => 'o';
const p = () => 'p';
const q = () => 'q';
const r = () => 'r';
const s = () => 's';
const t = () => 't';
const u = () => 'u';
const v = () => 'v';
const w = () => 'w';
const x = () => 'x';
const y = () => 'y';
const z = () => 'z';

const hello = () => {
    a();
    b();
    c();
    d();
    e();
    f();
    g();
    h();
    i();
    j();
    k();
    l();
    m();
    n();
    o();
    p();
    q();
    r();
    s();
    t();
    u();
    v();
    w();
    x();
    y();
    z();

    return 'hello';
};

export default hello;
